networks:
  genlab_network:
    driver: bridge
services:
  genlab_fe:
    image: gflai2/genlab_fe:1.0.0
    networks:
    - genlab_network
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ~/ssl:/etc/nginx/ssl
version: '3.8'
