networks:
  genlab_network:
    driver: bridge
services:
  genlab_fe:
    image: gflai2/genlab_fe:1.0.0
    networks:
    - genlab_network
    ports:
    - 8080:80
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
version: '3.8'
