networks:
  gmr_fe_network:
    driver: bridge
services:
  gmr_fe:
    image: harbor.sltung.com.tw/medical_history/gmr_fe:1.4.10
    networks:
    - gmr_fe_network
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ~/ssl:/etc/nginx/ssl
version: '3.8'
